#!/bin/bash

log=run-dilithium-libjade.log

# run tests (and bench) for dilithium{2,3,5}/{ref,avx2} from pq-crystals
echo -n "" > $log
for param in 2 3 5
do
  for implementation in ref avx2
  do
    ./do-part crypto_sign dilithium${param}-head libjade-$implementation
    echo -e "\ncrypto_sign/dilithium${param}/libjade-${implementation}:"
    grep " try " $(find bench/ -name data) | cut -d' ' -f9,13 >> $log
  done
done
